CU-860rn0rmj - Profile dropdown
raqamli/kwiz-dashboard pull request #4
Opened 2023-08-30 12:36 UTC by sarvar-swe

2023-08-30 12:36 UTC, wahid-d commented
Task linked: [CU-860rn0rmj Profile dropdown](https://app.clickup.com/t/860rn0rmj)

2023-09-06 07:47 UTC, wahid-d requested changes

2023-09-06 07:47 UTC, wahid-d commented on Kwiz.Dashboard.csproj
> +    <PackageReference Include="Keycloak.AuthServices.Sdk" Version="1.5.2" /> -->
Kerak bo'lmasa o'chirvoring

2023-09-06 07:47 UTC, wahid-d commented on Shared/LoginDisplay.razor
> -        Navigation.NavigateToLogout("authentication/logout");
Kerak bolmasa komentlarni o'chirvoring

2023-09-06 07:47 UTC, wahid-d commented on Shared/LoginDisplay.razor
> +        Navigation.NavigateToLogout("https://auth.xloyiha.tech/admin/xloyiha/console");
Bu yerga navigate qilsangiz aniq logout qilyaptimi?

Bu yerga navigate qilgandan keyin, boshqa oynada yana quiz dashboardni ochib ko'ring. Agar login ga redirect qilmasa demak logout qilmagan bol'adi.

2023-09-06 07:47 UTC, wahid-d commented on Components/Header/ProfileDropdownComponent.cs
> +        Navigation.NavigateToLogout("https://auth.xloyiha.tech/realms/xloyiha/protocol/openid-connect/logout");
QOyil: Manabu URL ni configuration dan olish kaerk. Appseetings ga joylang

2023-09-06 07:47 UTC, wahid-d commented on Shared/LoginDisplay.razor
Manaimcha bozga LoginDisplay kerak bolmasa kerak. Shuni o'rganingchi

2023-09-06 17:53 UTC, sarvar-swe commented on Shared/LoginDisplay.razor
Agar LoginDisplayni ochirsam, profiledrowpdown ko'rinmay qolyapti

2023-09-06 18:02 UTC, merged